version: "2"
services:
  torrserver:
    image: alexks02/torrserver
    container_name: torrserver-amd64
    build:
      context: .
      dockerfile: ./Dockerfile.amd64
  torrserver-armhf:
    image: alexks02/torrserver:armhf
    container_name: torrserver-armhf
    build:
      context: .
      dockerfile: ./Dockerfile.armhf
