version: "2"
services:
  torrserver:
    image: alexks02/torrserver:latest
    container_name: torrserver
    build:
      context: .
      dockerfile: ./Dockerfile.amd64
  torrserver-armhf:
    image: alexks02/torrserver:armhf
    container_name: torrserver
    build:
      context: .
      dockerfile: ./Dockerfile.armhf
